// export var arguments: any;
export var thisProgram: string;
export var quit: any;
export var preRun: any;
export var postRun: any;
export var read: any;
export var readBinary: any;
export var inspect: any;
export var HEAP8: any;
export var HEAP16: any;
export var HEAP32: any;
export var HEAPU8: any;
export var HEAPU16: any;
export var HEAPU32: any;
export var HEAPF32: any;
export var HEAPF64: any;
export var preloadedImages: any;
export var preloadedAudios: any;
export var asm: any;
export var requestFullScreen: any;
export var requestFullscreen: any;
export var requestAnimationFrame: any;
export var setCanvasSize: any;
export var pauseMainLoop: any;
export var resumeMainLoop: any;
export var getUserMedia: any;
export var createContext: any;
export var FS_createFolder: any;
export var FS_createPath: any;
// export var FS_createDataFile: any;
export var FS_createPreloadedFile: any;
export var FS_createLazyFile: any;
export var FS_createLink: any;
export var FS_createDevice: any;
export var FS_unlink: any;
// export var InternalError: any;
// export var BindingError: any;
// export var getInheritedInstanceCount: any;
// export var getLiveInheritedInstances: any;
// export var flushPendingDeletes: any;
// export var setDelayFunction: any;
// export var UnboundTypeError: any;
export var count_emval_handles: any;
export var get_first_emval: any;
export var __ZSt18uncaught_exceptionv: any;
export var ___cxa_can_catch: any;
export var ___cxa_demangle: any;
export var ___cxa_is_pointer_type: any;
export var ___errno_location: any;
export var ___getTypeName: any;
export var __get_environ: any;
export var _emscripten_replace_memory: any;
export var _free: any;
export var _llvm_bswap_i32: any;
export var _malloc: any;
export var _memcpy: any;
export var _memmove: any;
export var _memset: any;
export var _pthread_cond_broadcast: any;
export var _rintf: any;
export var _sbrk: any;
export var establishStackSpace: any;
export var globalCtors: any;
export var stackAlloc: any;
export var stackRestore: any;
export var stackSave: any;
export var dynCall_di: any;
export var dynCall_dii: any;
export var dynCall_diiddi: any;
export var dynCall_diii: any;
export var dynCall_diiid: any;
export var dynCall_diiiddi: any;
export var dynCall_diiii: any;
export var dynCall_diiiid: any;
export var dynCall_diiiii: any;
export var dynCall_diiiiii: any;
export var dynCall_diiiiiii: any;
export var dynCall_diiiiiiii: any;
export var dynCall_diiiiiiiiii: any;
export var dynCall_diiiiiiiiiii: any;
export var dynCall_diiiiiiiiiiii: any;
export var dynCall_diiiiiiiiiiiii: any;
export var dynCall_fi: any;
export var dynCall_fii: any;
export var dynCall_fiii: any;
export var dynCall_fiiii: any;
export var dynCall_fiiiii: any;
export var dynCall_i: any;
export var dynCall_ii: any;
export var dynCall_iid: any;
export var dynCall_iidi: any;
export var dynCall_iidiiii: any;
export var dynCall_iif: any;
export var dynCall_iiff: any;
export var dynCall_iifff: any;
export var dynCall_iiffff: any;
export var dynCall_iii: any;
export var dynCall_iiid: any;
export var dynCall_iiidd: any;
export var dynCall_iiiddi: any;
export var dynCall_iiiddii: any;
export var dynCall_iiiddiid: any;
export var dynCall_iiiddiiid: any;
export var dynCall_iiidi: any;
export var dynCall_iiidii: any;
export var dynCall_iiidiii: any;
export var dynCall_iiidiiii: any;
export var dynCall_iiidiiiii: any;
export var dynCall_iiif: any;
export var dynCall_iiifi: any;
export var dynCall_iiifii: any;
export var dynCall_iiifiii: any;
export var dynCall_iiifiiii: any;
export var dynCall_iiifiiiii: any;
export var dynCall_iiifiiiiii: any;
export var dynCall_iiifiiiiiii: any;
export var dynCall_iiii: any;
export var dynCall_iiiid: any;
export var dynCall_iiiif: any;
export var dynCall_iiiiff: any;
export var dynCall_iiiiffi: any;
export var dynCall_iiiifi: any;
export var dynCall_iiiifii: any;
export var dynCall_iiiifiii: any;
export var dynCall_iiiii: any;
export var dynCall_iiiiid: any;
export var dynCall_iiiiidd: any;
export var dynCall_iiiiiddi: any;
export var dynCall_iiiiiddid: any;
export var dynCall_iiiiiddidd: any;
export var dynCall_iiiiiddiddi: any;
export var dynCall_iiiiidi: any;
export var dynCall_iiiiidii: any;
export var dynCall_iiiiidiid: any;
export var dynCall_iiiiif: any;
export var dynCall_iiiiifi: any;
export var dynCall_iiiiifii: any;
export var dynCall_iiiiifiii: any;
export var dynCall_iiiiii: any;
export var dynCall_iiiiiid: any;
export var dynCall_iiiiiidi: any;
export var dynCall_iiiiiidid: any;
export var dynCall_iiiiiididi: any;
export var dynCall_iiiiiiff: any;
export var dynCall_iiiiiiffi: any;
export var dynCall_iiiiiifiididiii: any;
export var dynCall_iiiiiii: any;
export var dynCall_iiiiiiii: any;
export var dynCall_iiiiiiiididiii: any;
export var dynCall_iiiiiiiii: any;
export var dynCall_iiiiiiiiii: any;
export var dynCall_iiiiiiiiiiiii: any;
export var dynCall_iiiiij: any;
export var dynCall_ji: any;
export var dynCall_jii: any;
export var dynCall_jiii: any;
export var dynCall_jiiii: any;
export var dynCall_jiji: any;
export var dynCall_v: any;
export var dynCall_vdii: any;
export var dynCall_vdiii: any;
export var dynCall_vi: any;
export var dynCall_vid: any;
export var dynCall_vidi: any;
export var dynCall_vididdi: any;
export var dynCall_vididdii: any;
export var dynCall_vidii: any;
export var dynCall_vidiii: any;
export var dynCall_vif: any;
export var dynCall_viff: any;
export var dynCall_vifff: any;
export var dynCall_viffff: any;
export var dynCall_vifi: any;
export var dynCall_vii: any;
export var dynCall_viid: any;
export var dynCall_viidd: any;
export var dynCall_viiddi: any;
export var dynCall_viiddid: any;
export var dynCall_viiddidd: any;
export var dynCall_viiddiddd: any;
export var dynCall_viiddidddd: any;
export var dynCall_viiddii: any;
export var dynCall_viiddiid: any;
export var dynCall_viiddiii: any;
export var dynCall_viiddiiid: any;
export var dynCall_viidi: any;
export var dynCall_viididdi: any;
export var dynCall_viididdii: any;
export var dynCall_viididi: any;
export var dynCall_viididii: any;
export var dynCall_viidii: any;
export var dynCall_viidiii: any;
export var dynCall_viidiiid: any;
export var dynCall_viidiiii: any;
export var dynCall_viidiiiii: any;
export var dynCall_viif: any;
export var dynCall_viifi: any;
export var dynCall_viifii: any;
export var dynCall_viifiii: any;
export var dynCall_viifiiii: any;
export var dynCall_viifiiiii: any;
export var dynCall_viifiiiiii: any;
export var dynCall_viifiiiiiii: any;
export var dynCall_viii: any;
export var dynCall_viiid: any;
export var dynCall_viiidd: any;
export var dynCall_viiiddd: any;
export var dynCall_viiidddd: any;
export var dynCall_viiiddddi: any;
export var dynCall_viiiddddii: any;
export var dynCall_viiidddi: any;
export var dynCall_viiidddii: any;
export var dynCall_viiidddiii: any;
export var dynCall_viiidddiiii: any;
export var dynCall_viiiddi: any;
export var dynCall_viiiddid: any;
export var dynCall_viiiddidd: any;
export var dynCall_viiiddiddd: any;
export var dynCall_viiiddidddd: any;
export var dynCall_viiiddii: any;
export var dynCall_viiiddiii: any;
export var dynCall_viiiddiiid: any;
export var dynCall_viiiddiiii: any;
export var dynCall_viiiddiiiid: any;
export var dynCall_viiidi: any;
export var dynCall_viiididi: any;
export var dynCall_viiididii: any;
export var dynCall_viiidii: any;
export var dynCall_viiidiiddi: any;
export var dynCall_viiidiii: any;
export var dynCall_viiidiiid: any;
export var dynCall_viiidiiii: any;
export var dynCall_viiidiiiidi: any;
export var dynCall_viiif: any;
export var dynCall_viiiff: any;
export var dynCall_viiiffi: any;
export var dynCall_viiifi: any;
export var dynCall_viiifii: any;
export var dynCall_viiifiii: any;
export var dynCall_viiii: any;
export var dynCall_viiiid: any;
export var dynCall_viiiidd: any;
export var dynCall_viiiiddd: any;
export var dynCall_viiiidddd: any;
export var dynCall_viiiiddddi: any;
export var dynCall_viiiiddddii: any;
export var dynCall_viiiidddi: any;
export var dynCall_viiiidddii: any;
export var dynCall_viiiidddiii: any;
export var dynCall_viiiidddiiii: any;
export var dynCall_viiiiddi: any;
export var dynCall_viiiiddid: any;
export var dynCall_viiiiddidd: any;
export var dynCall_viiiiddiddi: any;
export var dynCall_viiiiddii: any;
export var dynCall_viiiiddiii: any;
export var dynCall_viiiiddiiid: any;
export var dynCall_viiiiddiiii: any;
export var dynCall_viiiiddiiiid: any;
export var dynCall_viiiidi: any;
export var dynCall_viiiidii: any;
export var dynCall_viiiidiid: any;
export var dynCall_viiiidiidd: any;
export var dynCall_viiiidiiddi: any;
export var dynCall_viiiidiii: any;
export var dynCall_viiiidiiii: any;
export var dynCall_viiiidiiiidi: any;
export var dynCall_viiiif: any;
export var dynCall_viiiifi: any;
export var dynCall_viiiifii: any;
export var dynCall_viiiifiii: any;
export var dynCall_viiiii: any;
export var dynCall_viiiiid: any;
export var dynCall_viiiiidd: any;
export var dynCall_viiiiiddi: any;
export var dynCall_viiiiidi: any;
export var dynCall_viiiiidid: any;
export var dynCall_viiiiididi: any;
export var dynCall_viiiiidii: any;
export var dynCall_viiiiidiid: any;
export var dynCall_viiiiidiidd: any;
export var dynCall_viiiiidiiddi: any;
export var dynCall_viiiiidiii: any;
export var dynCall_viiiiidiiii: any;
export var dynCall_viiiiidiiiii: any;
export var dynCall_viiiiif: any;
export var dynCall_viiiiiff: any;
export var dynCall_viiiiiffi: any;
export var dynCall_viiiiifi: any;
export var dynCall_viiiiifii: any;
export var dynCall_viiiiii: any;
export var dynCall_viiiiiid: any;
export var dynCall_viiiiiidd: any;
export var dynCall_viiiiiiddi: any;
export var dynCall_viiiiiidi: any;
export var dynCall_viiiiiidii: any;
export var dynCall_viiiiiidiii: any;
export var dynCall_viiiiiidiiii: any;
export var dynCall_viiiiiidiiiii: any;
export var dynCall_viiiiiif: any;
export var dynCall_viiiiiifi: any;
export var dynCall_viiiiiii: any;
export var dynCall_viiiiiiid: any;
export var dynCall_viiiiiiidd: any;
export var dynCall_viiiiiiiddi: any;
export var dynCall_viiiiiiidi: any;
export var dynCall_viiiiiiii: any;
export var dynCall_viiiiiiiii: any;
export var dynCall_viiiiiiiiidd: any;
export var dynCall_viiiiiiiiii: any;
export var dynCall_viiiiiiiiiid: any;
export var dynCall_viiiiiiiiiiddi: any;
export var dynCall_viiiiiiiiiii: any;
export var dynCall_viiiiiiiiiiid: any;
export var dynCall_viiiij: any;
export var dynCall_viiij: any;
export var dynCall_viijii: any;
export var dynCall_vij: any;
export var dynCall_viji: any;
export var getMemory: any;
export var addRunDependency: any;
export var removeRunDependency: any;
export var then: any;
export var run: any;
export var abort: any;
export var noExitRuntime: any;
export var calledRun: any;
export var stdin: any;
export var stdout: any;
export var stderr: any;
// export var IntVector: any;
// export var FloatVector: any;
// export var DoubleVector: any;
// export var PointVector: any;
export var MatVector: any;
// export var RectVector: any;
// export var KeyPointVector: any;
// export var DMatchVector: any;
// export var DMatchVectorVector: any;
export var Mat: any;
export var rotatedRectPoints: any;
export var rotatedRectBoundingRect: any;
export var rotatedRectBoundingRect2f: any;
// export var exceptionFromPtr: any;
// export var minEnclosingCircle: any;
// export var floodFill: any;
// export var minMaxLoc: any;
// export var morphologyDefaultBorderValue: any;
export var CV_MAT_DEPTH: any;
// export var CamShift: any;
// export var meanShift: any;
// export var getBuildInformation: any;
// export var CV_8UC1: number;
// export var CV_8UC2: number;
// export var CV_8UC3: number;
// export var CV_8UC4: number;
// export var CV_8SC1: number;
// export var CV_8SC2: number;
// export var CV_8SC3: number;
// export var CV_8SC4: number;
// export var CV_16UC1: number;
// export var CV_16UC2: number;
// export var CV_16UC3: number;
// export var CV_16UC4: number;
// export var CV_16SC1: number;
// export var CV_16SC2: number;
// export var CV_16SC3: number;
// export var CV_16SC4: number;
// export var CV_32SC1: number;
// export var CV_32SC2: number;
// export var CV_32SC3: number;
// export var CV_32SC4: number;
// export var CV_32FC1: number;
// export var CV_32FC2: number;
// export var CV_32FC3: number;
// export var CV_32FC4: number;
// export var CV_64FC1: number;
// export var CV_64FC2: number;
// export var CV_64FC3: number;
// export var CV_64FC4: number;
// export var CV_8U: number;
// export var CV_8S: number;
// export var CV_16U: number;
// export var CV_16S: number;
// export var CV_32S: number;
// export var CV_32F: number;
// export var CV_64F: number;
export var INT_MIN: number;
export var INT_MAX: number;
// export var Canny: any;
export var Canny1: any;
// export var GaussianBlur: any;
// export var HoughCircles: any;
// export var HoughLines: any;
// export var HoughLinesP: any;
// export var Laplacian: any;
// export var Rodrigues: any;
// export var Scharr: any;
// export var Sobel: any;
// export var absdiff: any;
// export var adaptiveThreshold: any;
// export var add: any;
// export var addWeighted: any;
// export var approxPolyDP: any;
// export var arcLength: any;
// export var bilateralFilter: any;
// export var bitwise_and: any;
// export var bitwise_not: any;
// export var bitwise_or: any;
// export var bitwise_xor: any;
// export var blur: any;
// export var boundingRect: any;
// export var boxFilter: any;
// export var calcBackProject: any;
// export var calcHist: any;
// export var calcOpticalFlowFarneback: any;
// export var calcOpticalFlowPyrLK: any;
export var calibrateCameraExtended: any;
// export var cartToPolar: any;
// export var circle: any;
// export var compare: any;
// export var compareHist: any;
// export var connectedComponents: any;
// export var connectedComponentsWithStats: any;
// export var contourArea: any;
// export var convertScaleAbs: any;
// export var convexHull: any;
// export var convexityDefects: any;
// export var copyMakeBorder: any;
// export var cornerHarris: any;
// export var cornerMinEigenVal: any;
// export var countNonZero: any;
// export var cvtColor: any;
// export var demosaicing: any;
// export var determinant: any;
// export var dft: any;
// export var dilate: any;
// export var distanceTransform: any;
export var distanceTransformWithLabels: any;
// export var divide: any;
export var divide1: any;
// export var drawContours: any;
// export var drawFrameAxes: any;
// export var drawKeypoints: any;
// export var drawMatches: any;
export var drawMatchesKnn: any;
// export var eigen: any;
// export var ellipse: any;
// export var ellipse1: any;
// export var ellipse2Poly: any;
// export var equalizeHist: any;
// export var erode: any;
// export var estimateAffine2D: any;
// export var exp: any;
// export var fillConvexPoly: any;
// export var fillPoly: any;
// export var filter2D: any;
// export var findContours: any;
// export var findHomography: any;
// export var findTransformECC: any;
// export var fitEllipse: any;
// export var fitLine: any;
// export var flip: any;
// export var gemm: any;
// export var getAffineTransform: any;
// export var getDefaultNewCameraMatrix: any;
// export var getOptimalDFTSize: any;
// export var getPerspectiveTransform: any;
// export var getRotationMatrix2D: any;
// export var getStructuringElement: any;
// export var goodFeaturesToTrack: any;
export var goodFeaturesToTrack1: any;
// export var grabCut: any;
// export var groupRectangles: any;
// export var hconcat: any;
// export var inRange: any;
// export var initUndistortRectifyMap: any;
// export var inpaint: any;
// export var integral: any;
export var integral2: any;
// export var invert: any;
// export var isContourConvex: any;
// export var kmeans: any;
// export var line: any;
// export var log: any;
// export var magnitude: any;
// export var matchShapes: any;
// export var matchTemplate: any;
// export var max: any;
// export var mean: any;
// export var meanStdDev: any;
// export var medianBlur: any;
// export var merge: any;
// export var min: any;
// export var minAreaRect: any;
// export var mixChannels: any;
// export var moments: any;
// export var morphologyEx: any;
// export var multiply: any;
// export var norm: any;
// export var norm1: any;
// export var normalize: any;
// export var perspectiveTransform: any;
// export var pointPolygonTest: any;
// export var polarToCart: any;
// export var pow: any;
// export var putText: any;
// export var pyrDown: any;
// export var pyrUp: any;
// export var randn: any;
// export var randu: any;
// export var rectangle: any;
export var rectangle1: any;
// export var reduce: any;
// export var remap: any;
// export var repeat: any;
// export var resize: any;
// export var rotate: any;
// export var sepFilter2D: any;
// export var setIdentity: any;
// export var setRNGSeed: any;
// export var solve: any;
// export var solvePoly: any;
// export var split: any;
// export var sqrt: any;
// export var subtract: any;
// export var threshold: any;
// export var trace: any;
// export var transform: any;
// export var transpose: any;
// export var undistort: any;
// export var vconcat: any;
// export var warpAffine: any;
// export var warpPerspective: any;
// export var warpPolar: any;
// export var watershed: any;
// export var blobFromImage: any;
// export var readNet: any;
export var readNet1: any;
// export var readNetFromCaffe: any;
export var readNetFromCaffe1: any;
// export var readNetFromDarknet: any;
export var readNetFromDarknet1: any;
// export var readNetFromONNX: any;
export var readNetFromONNX1: any;
// export var readNetFromTensorflow: any;
export var readNetFromTensorflow1: any;
// export var readNetFromTorch: any;
export var MergeMertens: any;
export var CalibrateRobertson: any;
export var dnn_Net: any;
export var MergeDebevec: any;
export var BackgroundSubtractor: any;
export var AlignMTB: any;
// export var HOGDescriptor: any;
export var KAZE: any;
export var BackgroundSubtractorMOG2: any;
export var TonemapMantiuk: any;
export var Tonemap: any;
// export var CLAHE: any;
export var CalibrateCRF: any;
export var AKAZE: any;
export var MergeExposures: any;
export var CalibrateDebevec: any;
// export var Algorithm: any;
export var Feature2D: any;
export var MergeRobertson: any;
export var GFTTDetector: any;
// export var DescriptorMatcher: any;
export var MSER: any;
// export var BFMatcher: any;
export var FastFeatureDetector: any;
export var AgastFeatureDetector: any;
// export var CascadeClassifier: any;
export var TonemapReinhard: any;
export var TonemapDrago: any;
export var ORB: any;
export var BRISK: any;
export var ACCESS_FAST: number;
export var ACCESS_MASK: number;
export var ACCESS_READ: number;
export var ACCESS_RW: number;
export var ACCESS_WRITE: number;
// export var ADAPTIVE_THRESH_GAUSSIAN_C: number;
// export var ADAPTIVE_THRESH_MEAN_C: number;
export var AKAZE_DESCRIPTOR_KAZE: number;
export var AKAZE_DESCRIPTOR_KAZE_UPRIGHT: number;
export var AKAZE_DESCRIPTOR_MLDB: number;
export var AKAZE_DESCRIPTOR_MLDB_UPRIGHT: number;
export var AgastFeatureDetector_AGAST_5_8: number;
export var AgastFeatureDetector_AGAST_7_12d: number;
export var AgastFeatureDetector_AGAST_7_12s: number;
export var AgastFeatureDetector_NONMAX_SUPPRESSION: number;
export var AgastFeatureDetector_OAST_9_16: number;
export var AgastFeatureDetector_THRESHOLD: number;
// export var BORDER_CONSTANT: number;
// export var BORDER_DEFAULT: number;
// export var BORDER_ISOLATED: number;
// export var BORDER_REFLECT: number;
// export var BORDER_REFLECT101: number;
// export var BORDER_REFLECT_101: number;
// export var BORDER_REPLICATE: number;
// export var BORDER_TRANSPARENT: number;
// export var BORDER_WRAP: number;
// export var CALIB_CB_ACCURACY: number;
// export var CALIB_CB_ADAPTIVE_THRESH: number;
// export var CALIB_CB_ASYMMETRIC_GRID: number;
// export var CALIB_CB_CLUSTERING: number;
// export var CALIB_CB_EXHAUSTIVE: number;
// export var CALIB_CB_FAST_CHECK: number;
// export var CALIB_CB_FILTER_QUADS: number;
export var CALIB_CB_LARGER: number;
export var CALIB_CB_MARKER: number;
// export var CALIB_CB_NORMALIZE_IMAGE: number;
// export var CALIB_CB_SYMMETRIC_GRID: number;
// export var CALIB_FIX_ASPECT_RATIO: number;
// export var CALIB_FIX_FOCAL_LENGTH: number;
// export var CALIB_FIX_INTRINSIC: number;
// export var CALIB_FIX_K1: number;
// export var CALIB_FIX_K2: number;
// export var CALIB_FIX_K3: number;
// export var CALIB_FIX_K4: number;
// export var CALIB_FIX_K5: number;
// export var CALIB_FIX_K6: number;
// export var CALIB_FIX_PRINCIPAL_POINT: number;
// export var CALIB_FIX_S1_S2_S3_S4: number;
// export var CALIB_FIX_TANGENT_DIST: number;
// export var CALIB_FIX_TAUX_TAUY: number;
// export var CALIB_HAND_EYE_ANDREFF: number;
// export var CALIB_HAND_EYE_DANIILIDIS: number;
// export var CALIB_HAND_EYE_HORAUD: number;
// export var CALIB_HAND_EYE_PARK: number;
// export var CALIB_HAND_EYE_TSAI: number;
// export var CALIB_NINTRINSIC: number;
// export var CALIB_RATIONAL_MODEL: number;
// export var CALIB_SAME_FOCAL_LENGTH: number;
// export var CALIB_THIN_PRISM_MODEL: number;
// export var CALIB_TILTED_MODEL: number;
// export var CALIB_USE_EXTRINSIC_GUESS: number;
// export var CALIB_USE_INTRINSIC_GUESS: number;
// export var CALIB_USE_LU: number;
// export var CALIB_USE_QR: number;
// export var CALIB_ZERO_DISPARITY: number;
// export var CALIB_ZERO_TANGENT_DIST: number;
// export var CASCADE_DO_CANNY_PRUNING: number;
// export var CASCADE_DO_ROUGH_SEARCH: number;
// export var CASCADE_FIND_BIGGEST_OBJECT: number;
// export var CASCADE_SCALE_IMAGE: number;
// export var CCL_DEFAULT: number;
// export var CCL_GRANA: number;
// export var CCL_WU: number;
// export var CC_STAT_AREA: number;
// export var CC_STAT_HEIGHT: number;
// export var CC_STAT_LEFT: number;
// export var CC_STAT_MAX: number;
// export var CC_STAT_TOP: number;
// export var CC_STAT_WIDTH: number;
// export var CHAIN_APPROX_NONE: number;
// export var CHAIN_APPROX_SIMPLE: number;
// export var CHAIN_APPROX_TC89_KCOS: number;
// export var CHAIN_APPROX_TC89_L1: number;
// export var CMP_EQ: number;
// export var CMP_GE: number;
// export var CMP_GT: number;
// export var CMP_LE: number;
// export var CMP_LT: number;
// export var CMP_NE: number;
export var COLORMAP_AUTUMN: number;
export var COLORMAP_BONE: number;
export var COLORMAP_CIVIDIS: number;
export var COLORMAP_COOL: number;
export var COLORMAP_HOT: number;
export var COLORMAP_HSV: number;
export var COLORMAP_INFERNO: number;
export var COLORMAP_JET: number;
export var COLORMAP_MAGMA: number;
export var COLORMAP_OCEAN: number;
export var COLORMAP_PARULA: number;
export var COLORMAP_PINK: number;
export var COLORMAP_PLASMA: number;
export var COLORMAP_RAINBOW: number;
export var COLORMAP_SPRING: number;
export var COLORMAP_SUMMER: number;
export var COLORMAP_TURBO: number;
export var COLORMAP_TWILIGHT: number;
export var COLORMAP_TWILIGHT_SHIFTED: number;
export var COLORMAP_VIRIDIS: number;
export var COLORMAP_WINTER: number;
// export var COLOR_BGR2BGR555: number;
// export var COLOR_BGR2BGR565: number;
// export var COLOR_BGR2BGRA: number;
// export var COLOR_BGR2GRAY: number;
// export var COLOR_BGR2HLS: number;
// export var COLOR_BGR2HLS_FULL: number;
// export var COLOR_BGR2HSV: number;
// export var COLOR_BGR2HSV_FULL: number;
// export var COLOR_BGR2Lab: number;
// export var COLOR_BGR2Luv: number;
// export var COLOR_BGR2RGB: number;
// export var COLOR_BGR2RGBA: number;
// export var COLOR_BGR2XYZ: number;
// export var COLOR_BGR2YCrCb: number;
// export var COLOR_BGR2YUV: number;
// export var COLOR_BGR2YUV_I420: number;
// export var COLOR_BGR2YUV_IYUV: number;
// export var COLOR_BGR2YUV_YV12: number;
// export var COLOR_BGR5552BGR: number;
// export var COLOR_BGR5552BGRA: number;
// export var COLOR_BGR5552GRAY: number;
// export var COLOR_BGR5552RGB: number;
// export var COLOR_BGR5552RGBA: number;
// export var COLOR_BGR5652BGR: number;
// export var COLOR_BGR5652BGRA: number;
// export var COLOR_BGR5652GRAY: number;
// export var COLOR_BGR5652RGB: number;
// export var COLOR_BGR5652RGBA: number;
// export var COLOR_BGRA2BGR: number;
// export var COLOR_BGRA2BGR555: number;
// export var COLOR_BGRA2BGR565: number;
// export var COLOR_BGRA2GRAY: number;
// export var COLOR_BGRA2RGB: number;
// export var COLOR_BGRA2RGBA: number;
// export var COLOR_BGRA2YUV_I420: number;
// export var COLOR_BGRA2YUV_IYUV: number;
// export var COLOR_BGRA2YUV_YV12: number;
// export var COLOR_BayerBG2BGR: number;
// export var COLOR_BayerBG2BGRA: number;
// export var COLOR_BayerBG2BGR_EA: number;
// export var COLOR_BayerBG2BGR_VNG: number;
// export var COLOR_BayerBG2GRAY: number;
// export var COLOR_BayerBG2RGB: number;
// export var COLOR_BayerBG2RGBA: number;
// export var COLOR_BayerBG2RGB_EA: number;
// export var COLOR_BayerBG2RGB_VNG: number;
// export var COLOR_BayerGB2BGR: number;
// export var COLOR_BayerGB2BGRA: number;
// export var COLOR_BayerGB2BGR_EA: number;
// export var COLOR_BayerGB2BGR_VNG: number;
// export var COLOR_BayerGB2GRAY: number;
// export var COLOR_BayerGB2RGB: number;
// export var COLOR_BayerGB2RGBA: number;
// export var COLOR_BayerGB2RGB_EA: number;
// export var COLOR_BayerGB2RGB_VNG: number;
// export var COLOR_BayerGR2BGR: number;
// export var COLOR_BayerGR2BGRA: number;
// export var COLOR_BayerGR2BGR_EA: number;
// export var COLOR_BayerGR2BGR_VNG: number;
// export var COLOR_BayerGR2GRAY: number;
// export var COLOR_BayerGR2RGB: number;
// export var COLOR_BayerGR2RGBA: number;
// export var COLOR_BayerGR2RGB_EA: number;
// export var COLOR_BayerGR2RGB_VNG: number;
// export var COLOR_BayerRG2BGR: number;
// export var COLOR_BayerRG2BGRA: number;
// export var COLOR_BayerRG2BGR_EA: number;
// export var COLOR_BayerRG2BGR_VNG: number;
// export var COLOR_BayerRG2GRAY: number;
// export var COLOR_BayerRG2RGB: number;
// export var COLOR_BayerRG2RGBA: number;
// export var COLOR_BayerRG2RGB_EA: number;
// export var COLOR_BayerRG2RGB_VNG: number;
// export var COLOR_COLORCVT_MAX: number;
// export var COLOR_GRAY2BGR: number;
// export var COLOR_GRAY2BGR555: number;
// export var COLOR_GRAY2BGR565: number;
// export var COLOR_GRAY2BGRA: number;
// export var COLOR_GRAY2RGB: number;
// export var COLOR_GRAY2RGBA: number;
// export var COLOR_HLS2BGR: number;
// export var COLOR_HLS2BGR_FULL: number;
// export var COLOR_HLS2RGB: number;
// export var COLOR_HLS2RGB_FULL: number;
// export var COLOR_HSV2BGR: number;
// export var COLOR_HSV2BGR_FULL: number;
// export var COLOR_HSV2RGB: number;
// export var COLOR_HSV2RGB_FULL: number;
// export var COLOR_LBGR2Lab: number;
// export var COLOR_LBGR2Luv: number;
// export var COLOR_LRGB2Lab: number;
// export var COLOR_LRGB2Luv: number;
// export var COLOR_Lab2BGR: number;
// export var COLOR_Lab2LBGR: number;
// export var COLOR_Lab2LRGB: number;
// export var COLOR_Lab2RGB: number;
// export var COLOR_Luv2BGR: number;
// export var COLOR_Luv2LBGR: number;
// export var COLOR_Luv2LRGB: number;
// export var COLOR_Luv2RGB: number;
// export var COLOR_RGB2BGR: number;
// export var COLOR_RGB2BGR555: number;
// export var COLOR_RGB2BGR565: number;
// export var COLOR_RGB2BGRA: number;
// export var COLOR_RGB2GRAY: number;
// export var COLOR_RGB2HLS: number;
// export var COLOR_RGB2HLS_FULL: number;
// export var COLOR_RGB2HSV: number;
// export var COLOR_RGB2HSV_FULL: number;
// export var COLOR_RGB2Lab: number;
// export var COLOR_RGB2Luv: number;
// export var COLOR_RGB2RGBA: number;
// export var COLOR_RGB2XYZ: number;
// export var COLOR_RGB2YCrCb: number;
// export var COLOR_RGB2YUV: number;
// export var COLOR_RGB2YUV_I420: number;
// export var COLOR_RGB2YUV_IYUV: number;
// export var COLOR_RGB2YUV_YV12: number;
// export var COLOR_RGBA2BGR: number;
// export var COLOR_RGBA2BGR555: number;
// export var COLOR_RGBA2BGR565: number;
// export var COLOR_RGBA2BGRA: number;
// export var COLOR_RGBA2GRAY: number;
// export var COLOR_RGBA2RGB: number;
// export var COLOR_RGBA2YUV_I420: number;
// export var COLOR_RGBA2YUV_IYUV: number;
// export var COLOR_RGBA2YUV_YV12: number;
// export var COLOR_RGBA2mRGBA: number;
// export var COLOR_XYZ2BGR: number;
// export var COLOR_XYZ2RGB: number;
// export var COLOR_YCrCb2BGR: number;
// export var COLOR_YCrCb2RGB: number;
// export var COLOR_YUV2BGR: number;
// export var COLOR_YUV2BGRA_I420: number;
// export var COLOR_YUV2BGRA_IYUV: number;
// export var COLOR_YUV2BGRA_NV12: number;
// export var COLOR_YUV2BGRA_NV21: number;
// export var COLOR_YUV2BGRA_UYNV: number;
// export var COLOR_YUV2BGRA_UYVY: number;
// export var COLOR_YUV2BGRA_Y422: number;
// export var COLOR_YUV2BGRA_YUNV: number;
// export var COLOR_YUV2BGRA_YUY2: number;
// export var COLOR_YUV2BGRA_YUYV: number;
// export var COLOR_YUV2BGRA_YV12: number;
// export var COLOR_YUV2BGRA_YVYU: number;
// export var COLOR_YUV2BGR_I420: number;
// export var COLOR_YUV2BGR_IYUV: number;
// export var COLOR_YUV2BGR_NV12: number;
// export var COLOR_YUV2BGR_NV21: number;
// export var COLOR_YUV2BGR_UYNV: number;
// export var COLOR_YUV2BGR_UYVY: number;
// export var COLOR_YUV2BGR_Y422: number;
// export var COLOR_YUV2BGR_YUNV: number;
// export var COLOR_YUV2BGR_YUY2: number;
// export var COLOR_YUV2BGR_YUYV: number;
// export var COLOR_YUV2BGR_YV12: number;
// export var COLOR_YUV2BGR_YVYU: number;
// export var COLOR_YUV2GRAY_420: number;
// export var COLOR_YUV2GRAY_I420: number;
// export var COLOR_YUV2GRAY_IYUV: number;
// export var COLOR_YUV2GRAY_NV12: number;
// export var COLOR_YUV2GRAY_NV21: number;
// export var COLOR_YUV2GRAY_UYNV: number;
// export var COLOR_YUV2GRAY_UYVY: number;
// export var COLOR_YUV2GRAY_Y422: number;
// export var COLOR_YUV2GRAY_YUNV: number;
// export var COLOR_YUV2GRAY_YUY2: number;
// export var COLOR_YUV2GRAY_YUYV: number;
// export var COLOR_YUV2GRAY_YV12: number;
// export var COLOR_YUV2GRAY_YVYU: number;
// export var COLOR_YUV2RGB: number;
// export var COLOR_YUV2RGBA_I420: number;
// export var COLOR_YUV2RGBA_IYUV: number;
// export var COLOR_YUV2RGBA_NV12: number;
// export var COLOR_YUV2RGBA_NV21: number;
// export var COLOR_YUV2RGBA_UYNV: number;
// export var COLOR_YUV2RGBA_UYVY: number;
// export var COLOR_YUV2RGBA_Y422: number;
// export var COLOR_YUV2RGBA_YUNV: number;
// export var COLOR_YUV2RGBA_YUY2: number;
// export var COLOR_YUV2RGBA_YUYV: number;
// export var COLOR_YUV2RGBA_YV12: number;
// export var COLOR_YUV2RGBA_YVYU: number;
// export var COLOR_YUV2RGB_I420: number;
// export var COLOR_YUV2RGB_IYUV: number;
// export var COLOR_YUV2RGB_NV12: number;
// export var COLOR_YUV2RGB_NV21: number;
// export var COLOR_YUV2RGB_UYNV: number;
// export var COLOR_YUV2RGB_UYVY: number;
// export var COLOR_YUV2RGB_Y422: number;
// export var COLOR_YUV2RGB_YUNV: number;
// export var COLOR_YUV2RGB_YUY2: number;
// export var COLOR_YUV2RGB_YUYV: number;
// export var COLOR_YUV2RGB_YV12: number;
// export var COLOR_YUV2RGB_YVYU: number;
// export var COLOR_YUV420p2BGR: number;
// export var COLOR_YUV420p2BGRA: number;
// export var COLOR_YUV420p2GRAY: number;
// export var COLOR_YUV420p2RGB: number;
// export var COLOR_YUV420p2RGBA: number;
// export var COLOR_YUV420sp2BGR: number;
// export var COLOR_YUV420sp2BGRA: number;
// export var COLOR_YUV420sp2GRAY: number;
// export var COLOR_YUV420sp2RGB: number;
// export var COLOR_YUV420sp2RGBA: number;
// export var COLOR_mRGBA2RGBA: number;
// export var CONTOURS_MATCH_I1: number;
// export var CONTOURS_MATCH_I2: number;
// export var CONTOURS_MATCH_I3: number;
export var COVAR_COLS: number;
export var COVAR_NORMAL: number;
export var COVAR_ROWS: number;
export var COVAR_SCALE: number;
export var COVAR_SCRAMBLED: number;
export var COVAR_USE_AVG: number;
export var CirclesGridFinderParameters_ASYMMETRIC_GRID: number;
export var CirclesGridFinderParameters_SYMMETRIC_GRID: number;
// export var DCT_INVERSE: number;
// export var DCT_ROWS: number;
// export var DECOMP_CHOLESKY: number;
// export var DECOMP_EIG: number;
// export var DECOMP_LU: number;
// export var DECOMP_NORMAL: number;
// export var DECOMP_QR: number;
// export var DECOMP_SVD: number;
// export var DFT_COMPLEX_INPUT: number;
// export var DFT_COMPLEX_OUTPUT: number;
// export var DFT_INVERSE: number;
// export var DFT_REAL_OUTPUT: number;
// export var DFT_ROWS: number;
// export var DFT_SCALE: number;
export var DISOpticalFlow_PRESET_FAST: number;
export var DISOpticalFlow_PRESET_MEDIUM: number;
export var DISOpticalFlow_PRESET_ULTRAFAST: number;
// export var DIST_C: number;
// export var DIST_FAIR: number;
// export var DIST_HUBER: number;
// export var DIST_L1: number;
// export var DIST_L12: number;
// export var DIST_L2: number;
// export var DIST_LABEL_CCOMP: number;
// export var DIST_LABEL_PIXEL: number;
// export var DIST_MASK_3: number;
// export var DIST_MASK_5: number;
// export var DIST_MASK_PRECISE: number;
// export var DIST_USER: number;
// export var DIST_WELSCH: number;
export var DescriptorMatcher_BRUTEFORCE: number;
export var DescriptorMatcher_BRUTEFORCE_HAMMING: number;
export var DescriptorMatcher_BRUTEFORCE_HAMMINGLUT: number;
export var DescriptorMatcher_BRUTEFORCE_L1: number;
export var DescriptorMatcher_BRUTEFORCE_SL2: number;
export var DescriptorMatcher_FLANNBASED: number;
export var DrawMatchesFlags_DEFAULT: number;
export var DrawMatchesFlags_DRAW_OVER_OUTIMG: number;
export var DrawMatchesFlags_DRAW_RICH_KEYPOINTS: number;
export var DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS: number;
// export var FILLED: number;
// export var FILTER_SCHARR: number;
// export var FLOODFILL_FIXED_RANGE: number;
// export var FLOODFILL_MASK_ONLY: number;
// export var FM_7POINT: number;
// export var FM_8POINT: number;
// export var FM_LMEDS: number;
// export var FM_RANSAC: number;
// export var FONT_HERSHEY_COMPLEX: number;
// export var FONT_HERSHEY_COMPLEX_SMALL: number;
// export var FONT_HERSHEY_DUPLEX: number;
// export var FONT_HERSHEY_PLAIN: number;
// export var FONT_HERSHEY_SCRIPT_COMPLEX: number;
// export var FONT_HERSHEY_SCRIPT_SIMPLEX: number;
// export var FONT_HERSHEY_SIMPLEX: number;
// export var FONT_HERSHEY_TRIPLEX: number;
// export var FONT_ITALIC: number;
export var FastFeatureDetector_FAST_N: number;
export var FastFeatureDetector_NONMAX_SUPPRESSION: number;
export var FastFeatureDetector_THRESHOLD: number;
export var FastFeatureDetector_TYPE_5_8: number;
export var FastFeatureDetector_TYPE_7_12: number;
export var FastFeatureDetector_TYPE_9_16: number;
export var FileNode_EMPTY: number;
export var FileNode_FLOAT: number;
export var FileNode_FLOW: number;
export var FileNode_INT: number;
export var FileNode_MAP: number;
export var FileNode_NAMED: number;
export var FileNode_NONE: number;
export var FileNode_REAL: number;
export var FileNode_SEQ: number;
export var FileNode_STR: number;
export var FileNode_STRING: number;
export var FileNode_TYPE_MASK: number;
export var FileNode_UNIFORM: number;
export var FileStorage_APPEND: number;
export var FileStorage_BASE64: number;
export var FileStorage_FORMAT_AUTO: number;
export var FileStorage_FORMAT_JSON: number;
export var FileStorage_FORMAT_MASK: number;
export var FileStorage_FORMAT_XML: number;
export var FileStorage_FORMAT_YAML: number;
export var FileStorage_INSIDE_MAP: number;
export var FileStorage_MEMORY: number;
export var FileStorage_NAME_EXPECTED: number;
export var FileStorage_READ: number;
export var FileStorage_UNDEFINED: number;
export var FileStorage_VALUE_EXPECTED: number;
export var FileStorage_WRITE: number;
export var FileStorage_WRITE_BASE64: number;
export var Formatter_FMT_C: number;
export var Formatter_FMT_CSV: number;
export var Formatter_FMT_DEFAULT: number;
export var Formatter_FMT_MATLAB: number;
export var Formatter_FMT_NUMPY: number;
export var Formatter_FMT_PYTHON: number;
// export var GC_BGD: number;
// export var GC_EVAL: number;
// export var GC_EVAL_FREEZE_MODEL: number;
// export var GC_FGD: number;
// export var GC_INIT_WITH_MASK: number;
// export var GC_INIT_WITH_RECT: number;
// export var GC_PR_BGD: number;
// export var GC_PR_FGD: number;
// export var GEMM_1_T: number;
// export var GEMM_2_T: number;
// export var GEMM_3_T: number;
// export var HISTCMP_BHATTACHARYYA: number;
// export var HISTCMP_CHISQR: number;
// export var HISTCMP_CHISQR_ALT: number;
// export var HISTCMP_CORREL: number;
// export var HISTCMP_HELLINGER: number;
// export var HISTCMP_INTERSECT: number;
// export var HISTCMP_KL_DIV: number;
export var HOGDescriptor_DEFAULT_NLEVELS: number;
export var HOGDescriptor_DESCR_FORMAT_COL_BY_COL: number;
export var HOGDescriptor_DESCR_FORMAT_ROW_BY_ROW: number;
export var HOGDescriptor_L2Hys: number;
// export var HOUGH_GRADIENT: number;
export var HOUGH_GRADIENT_ALT: number;
// export var HOUGH_MULTI_SCALE: number;
// export var HOUGH_PROBABILISTIC: number;
// export var HOUGH_STANDARD: number;
// export var INPAINT_NS: number;
// export var INPAINT_TELEA: number;
// export var INTERSECT_FULL: number;
// export var INTERSECT_NONE: number;
// export var INTERSECT_PARTIAL: number;
// export var INTER_AREA: number;
// export var INTER_BITS: number;
// export var INTER_BITS2: number;
// export var INTER_CUBIC: number;
// export var INTER_LANCZOS4: number;
// export var INTER_LINEAR: number;
// export var INTER_LINEAR_EXACT: number;
// export var INTER_MAX: number;
// export var INTER_NEAREST: number;
// export var INTER_TAB_SIZE: number;
// export var INTER_TAB_SIZE2: number;
export var KAZE_DIFF_CHARBONNIER: number;
export var KAZE_DIFF_PM_G1: number;
export var KAZE_DIFF_PM_G2: number;
export var KAZE_DIFF_WEICKERT: number;
export var KMEANS_PP_CENTERS: number;
export var KMEANS_RANDOM_CENTERS: number;
export var KMEANS_USE_INITIAL_LABELS: number;
export var LDR_SIZE: number;
// export var LINE_4: number;
// export var LINE_8: number;
// export var LINE_AA: number;
// export var LMEDS: number;
// export var LSD_REFINE_ADV: number;
// export var LSD_REFINE_NONE: number;
// export var LSD_REFINE_STD: number;
// export var MARKER_CROSS: number;
// export var MARKER_DIAMOND: number;
// export var MARKER_SQUARE: number;
// export var MARKER_STAR: number;
// export var MARKER_TILTED_CROSS: number;
// export var MARKER_TRIANGLE_DOWN: number;
// export var MARKER_TRIANGLE_UP: number;
export var MIXED_CLONE: number;
export var MONOCHROME_TRANSFER: number;
// export var MORPH_BLACKHAT: number;
// export var MORPH_CLOSE: number;
// export var MORPH_CROSS: number;
// export var MORPH_DILATE: number;
// export var MORPH_ELLIPSE: number;
// export var MORPH_ERODE: number;
// export var MORPH_GRADIENT: number;
// export var MORPH_HITMISS: number;
// export var MORPH_OPEN: number;
// export var MORPH_RECT: number;
// export var MORPH_TOPHAT: number;
// export var MOTION_AFFINE: number;
// export var MOTION_EUCLIDEAN: number;
// export var MOTION_HOMOGRAPHY: number;
// export var MOTION_TRANSLATION: number;
export var Mat_AUTO_STEP: number;
export var Mat_CONTINUOUS_FLAG: number;
export var Mat_DEPTH_MASK: number;
export var Mat_MAGIC_MASK: number;
export var Mat_MAGIC_VAL: number;
export var Mat_SUBMATRIX_FLAG: number;
export var Mat_TYPE_MASK: number;
export var NORMAL_CLONE: number;
export var NORMCONV_FILTER: number;
// export var NORM_HAMMING: number;
// export var NORM_HAMMING2: number;
// export var NORM_INF: number;
// export var NORM_L1: number;
// export var NORM_L2: number;
// export var NORM_L2SQR: number;
// export var NORM_MINMAX: number;
// export var NORM_RELATIVE: number;
// export var NORM_TYPE_MASK: number;
// export var OPTFLOW_FARNEBACK_GAUSSIAN: number;
// export var OPTFLOW_LK_GET_MIN_EIGENVALS: number;
// export var OPTFLOW_USE_INITIAL_FLOW: number;
export var ORB_FAST_SCORE: number;
export var ORB_HARRIS_SCORE: number;
export var PCA_DATA_AS_COL: number;
export var PCA_DATA_AS_ROW: number;
export var PCA_USE_AVG: number;
// export var PROJ_SPHERICAL_EQRECT: number;
// export var PROJ_SPHERICAL_ORTHO: number;
export var Param_ALGORITHM: number;
export var Param_BOOLEAN: number;
export var Param_FLOAT: number;
export var Param_INT: number;
export var Param_MAT: number;
export var Param_MAT_VECTOR: number;
export var Param_REAL: number;
export var Param_SCALAR: number;
export var Param_STRING: number;
export var Param_UCHAR: number;
export var Param_UINT64: number;
export var Param_UNSIGNED_INT: number;
// export var RANSAC: number;
export var RECURS_FILTER: number;
export var REDUCE_AVG: number;
export var REDUCE_MAX: number;
export var REDUCE_MIN: number;
export var REDUCE_SUM: number;
// export var RETR_CCOMP: number;
// export var RETR_EXTERNAL: number;
// export var RETR_FLOODFILL: number;
// export var RETR_LIST: number;
// export var RETR_TREE: number;
// export var RHO: number;
export var RNG_NORMAL: number;
export var RNG_UNIFORM: number;
// export var ROTATE_180: number;
// export var ROTATE_90_CLOCKWISE: number;
// export var ROTATE_90_COUNTERCLOCKWISE: number;
export var SOLVELP_MULTI: number;
export var SOLVELP_SINGLE: number;
export var SOLVELP_UNBOUNDED: number;
export var SOLVELP_UNFEASIBLE: number;
// export var SOLVEPNP_AP3P: number;
// export var SOLVEPNP_DLS: number;
// export var SOLVEPNP_EPNP: number;
// export var SOLVEPNP_IPPE: number;
// export var SOLVEPNP_IPPE_SQUARE: number;
// export var SOLVEPNP_ITERATIVE: number;
export var SOLVEPNP_MAX_COUNT: number;
// export var SOLVEPNP_P3P: number;
// export var SOLVEPNP_UPNP: number;
// export var SORT_ASCENDING: number;
// export var SORT_DESCENDING: number;
// export var SORT_EVERY_COLUMN: number;
// export var SORT_EVERY_ROW: number;
export var SVD_FULL_UV: number;
export var SVD_MODIFY_A: number;
export var SVD_NO_UV: number;
export var SparseMat_HASH_BIT: number;
export var SparseMat_HASH_SCALE: number;
export var SparseMat_MAGIC_VAL: number;
export var SparseMat_MAX_DIM: number;
export var StereoBM_PREFILTER_NORMALIZED_RESPONSE: number;
export var StereoBM_PREFILTER_XSOBEL: number;
export var StereoMatcher_DISP_SCALE: number;
export var StereoMatcher_DISP_SHIFT: number;
export var StereoSGBM_MODE_HH: number;
export var StereoSGBM_MODE_HH4: number;
export var StereoSGBM_MODE_SGBM: number;
export var StereoSGBM_MODE_SGBM_3WAY: number;
export var Subdiv2D_NEXT_AROUND_DST: number;
export var Subdiv2D_NEXT_AROUND_LEFT: number;
export var Subdiv2D_NEXT_AROUND_ORG: number;
export var Subdiv2D_NEXT_AROUND_RIGHT: number;
export var Subdiv2D_PREV_AROUND_DST: number;
export var Subdiv2D_PREV_AROUND_LEFT: number;
export var Subdiv2D_PREV_AROUND_ORG: number;
export var Subdiv2D_PREV_AROUND_RIGHT: number;
export var Subdiv2D_PTLOC_ERROR: number;
export var Subdiv2D_PTLOC_INSIDE: number;
export var Subdiv2D_PTLOC_ON_EDGE: number;
export var Subdiv2D_PTLOC_OUTSIDE_RECT: number;
export var Subdiv2D_PTLOC_VERTEX: number;
// export var THRESH_BINARY: number;
// export var THRESH_BINARY_INV: number;
// export var THRESH_MASK: number;
// export var THRESH_OTSU: number;
// export var THRESH_TOZERO: number;
// export var THRESH_TOZERO_INV: number;
// export var THRESH_TRIANGLE: number;
// export var THRESH_TRUNC: number;
// export var TM_CCOEFF: number;
// export var TM_CCOEFF_NORMED: number;
// export var TM_CCORR: number;
// export var TM_CCORR_NORMED: number;
// export var TM_SQDIFF: number;
// export var TM_SQDIFF_NORMED: number;
// export var TermCriteria_COUNT: number;
// export var TermCriteria_EPS: number;
// export var TermCriteria_MAX_ITER: number;
export var UMatData_ASYNC_CLEANUP: number;
export var UMatData_COPY_ON_MAP: number;
export var UMatData_DEVICE_COPY_OBSOLETE: number;
export var UMatData_DEVICE_MEM_MAPPED: number;
export var UMatData_HOST_COPY_OBSOLETE: number;
export var UMatData_TEMP_COPIED_UMAT: number;
export var UMatData_TEMP_UMAT: number;
export var UMatData_USER_ALLOCATED: number;
export var UMat_AUTO_STEP: number;
export var UMat_CONTINUOUS_FLAG: number;
export var UMat_DEPTH_MASK: number;
export var UMat_MAGIC_MASK: number;
export var UMat_MAGIC_VAL: number;
export var UMat_SUBMATRIX_FLAG: number;
export var UMat_TYPE_MASK: number;
export var USAGE_ALLOCATE_DEVICE_MEMORY: number;
export var USAGE_ALLOCATE_HOST_MEMORY: number;
export var USAGE_ALLOCATE_SHARED_MEMORY: number;
export var USAGE_DEFAULT: number;
// export var WARP_FILL_OUTLIERS: number;
// export var WARP_INVERSE_MAP: number;
// export var WARP_POLAR_LINEAR: number;
// export var WARP_POLAR_LOG: number;
export var _InputArray_CUDA_GPU_MAT: number;
export var _InputArray_CUDA_HOST_MEM: number;
export var _InputArray_EXPR: number;
export var _InputArray_FIXED_SIZE: number;
export var _InputArray_FIXED_TYPE: number;
export var _InputArray_KIND_MASK: number;
export var _InputArray_KIND_SHIFT: number;
export var _InputArray_MAT: number;
export var _InputArray_MATX: number;
export var _InputArray_NONE: number;
export var _InputArray_OPENGL_BUFFER: number;
export var _InputArray_STD_ARRAY: number;
export var _InputArray_STD_ARRAY_MAT: number;
export var _InputArray_STD_BOOL_VECTOR: number;
export var _InputArray_STD_VECTOR: number;
export var _InputArray_STD_VECTOR_CUDA_GPU_MAT: number;
export var _InputArray_STD_VECTOR_MAT: number;
export var _InputArray_STD_VECTOR_UMAT: number;
export var _InputArray_STD_VECTOR_VECTOR: number;
export var _InputArray_UMAT: number;
export var _OutputArray_DEPTH_MASK_16F: number;
export var _OutputArray_DEPTH_MASK_16S: number;
export var _OutputArray_DEPTH_MASK_16U: number;
export var _OutputArray_DEPTH_MASK_32F: number;
export var _OutputArray_DEPTH_MASK_32S: number;
export var _OutputArray_DEPTH_MASK_64F: number;
export var _OutputArray_DEPTH_MASK_8S: number;
export var _OutputArray_DEPTH_MASK_8U: number;
export var _OutputArray_DEPTH_MASK_ALL: number;
export var _OutputArray_DEPTH_MASK_ALL_16F: number;
export var _OutputArray_DEPTH_MASK_ALL_BUT_8S: number;
export var _OutputArray_DEPTH_MASK_FLT: number;
export var __UMAT_USAGE_FLAGS_32BIT: number;
export var BadAlign: number;
export var BadAlphaChannel: number;
export var BadCOI: number;
export var BadCallBack: number;
export var BadDataPtr: number;
export var BadDepth: number;
export var BadImageSize: number;
export var BadModelOrChSeq: number;
export var BadNumChannel1U: number;
export var BadNumChannels: number;
export var BadOffset: number;
export var BadOrder: number;
export var BadOrigin: number;
export var BadROISize: number;
export var BadStep: number;
export var BadTileSize: number;
export var GpuApiCallError: number;
export var GpuNotSupported: number;
export var HeaderIsNull: number;
export var MaskIsTiled: number;
export var OpenCLApiCallError: number;
export var OpenCLDoubleNotSupported: number;
export var OpenCLInitError: number;
export var OpenCLNoAMDBlasFft: number;
export var OpenGlApiCallError: number;
export var OpenGlNotSupported: number;
export var StsAssert: number;
export var StsAutoTrace: number;
export var StsBackTrace: number;
export var StsBadArg: number;
export var StsBadFlag: number;
export var StsBadFunc: number;
export var StsBadMask: number;
export var StsBadMemBlock: number;
export var StsBadPoint: number;
export var StsBadSize: number;
export var StsDivByZero: number;
export var StsError: number;
export var StsFilterOffsetErr: number;
export var StsFilterStructContentErr: number;
export var StsInplaceNotSupported: number;
export var StsInternal: number;
export var StsKernelStructContentErr: number;
export var StsNoConv: number;
export var StsNoMem: number;
export var StsNotImplemented: number;
export var StsNullPtr: number;
export var StsObjectNotFound: number;
export var StsOk: number;
export var StsOutOfRange: number;
export var StsParseError: number;
export var StsUnmatchedFormats: number;
export var StsUnmatchedSizes: number;
export var StsUnsupportedFormat: number;
export var StsVecLengthErr: number;
export var TEST_CUSTOM: number;
export var TEST_EQ: number;
export var TEST_GE: number;
export var TEST_GT: number;
export var TEST_LE: number;
export var TEST_LT: number;
export var TEST_NE: number;
export var DNN_BACKEND_CUDA: number;
// export var DNN_BACKEND_DEFAULT: number;
// export var DNN_BACKEND_HALIDE: number;
// export var DNN_BACKEND_INFERENCE_ENGINE: number;
// export var DNN_BACKEND_OPENCV: number;
// export var DNN_BACKEND_VKCOM: number;
// export var DNN_TARGET_CPU: number;
export var DNN_TARGET_CUDA: number;
export var DNN_TARGET_CUDA_FP16: number;
// export var DNN_TARGET_FPGA: number;
// export var DNN_TARGET_MYRIAD: number;
// export var DNN_TARGET_OPENCL: number;
// export var DNN_TARGET_OPENCL_FP16: number;
// export var DNN_TARGET_VULKAN: number;
export var CALIB_CHECK_COND: number;
export var CALIB_FIX_SKEW: number;
export var CALIB_RECOMPUTE_EXTRINSIC: number;
export var FS: any;
// export var imread: any;
// export var imshow: any;
// export var VideoCapture: any;
// export var Range: any;
// export var Point: any;
// export var Size: any;
// export var Rect: any;
// export var RotatedRect: any;
// export var Scalar: any;
// export var MinMaxLoc: any;
export var Circle: any;
// export var TermCriteria: any;
// export var matFromArray: any;
// export var matFromImageData: any;
